model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    dropout_encoder: 0.00001
    pretrained_encoder: True
    input_type: "images"
    topological_regularizer_settings:
      method: "deep" #=["match_scale_order","match_scale_distribution","moor_method","modified_moor_method","deep"] "og_moor"
      multithreading: True
      timeout: 1

                      
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 6
    val_split: 0.25
    k_fold : 4 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    input_type: "images"
    balance_dataset_classes: 50
    augmentation_settings: ["all",0.05]
    topo_settings:
      nb_of_grouped_bags: 1
      normalize_distance_matricies: True
      dataset_settings:
        grayscale: False
        encode_with_dino_bloom: True


exp_type: "topo_SCEMILA_experiment"
exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005184145793112568
      weight_decay: 0.00035
      factor: 0.25
      scheduler: "ReduceLROnPlateau"
      patience: 200
      monitor_metric: "val_correct_epoch"
      mode: "max"
    batch_size: 1
  label_smoothing:
    smoothing: 0.6
    per_epoch_decay: 0.98
    train_correct_threshold: 1.01 #never
  topo_scheduler:
    type: "constant"
    lam: 0.1

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 300
  enable_progress_bar: False
  accumulate_grad_batches: 8

logging_params:
  project_name: "topo_reg_testing"
  save_dir: "logs/topo_dino_image_input_experiment/"
  name: "eucl_dino_deep_topo_test"
  manual_seed: 1265


ES_params:
  monitor: 'val_correct_epoch'
  min_delta: 0.01
  patience: 250
  mode: 'max'
