model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    input_type: "fnl34"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 4
    k_fold : -1 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    data_type: "fnl34"
    topo_settings:
      nb_of_grouped_bags: 5
      dataset_settings:
        grayscale: False
        encode_with_dino_bloom: True
      embedding_settings:
        function_name: "UMAP"
        function_settings:
          n_components: 8


exp_type: "topo_SCEMILA_experiment"


exp_params:
  num_class: 5
  optimizer: 
    name: "Adam"
    config:
      LR: 0.000005
    batch_size: 1

trainer_params:
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 30
  accumulate_grad_batches : 1

logging_params:
  project_name: "Masters_Project"
  save_dir: "logs/topo_dino_fnl34_input_experiment/"
  name: "topo_dino_fnl34_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: "val_loss"
  min_delta: 0.1
  patience: 2
