model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cpu"
    dropout_encoder: 0.2
    pretrained_encoder: False
    input_type: "images"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 2
    k_fold : -1 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    val_split: 0.25
    input_type: "images"
    gpu: False
    balance_dataset_classes: 3
    augmentation_settings: ["all",0.5]
    topo_settings:
      nb_of_grouped_bags: 3
      normalize_distance_matricies: False
      dataset_settings:
        grayscale: True
        encode_with_dino_bloom: False
      embedding_settings:
        function_name: "UMAP"
        function_settings:
          n_components: 2


exp_type: "topo_SCEMILA_experiment"

exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.0001
      weight_decay: 0.00006
      scheduler: "ReduceLROnPlateau"
      patience: 8
      factor: 0.5
      monitor_metric: "val_mil_loss"
    batch_size: 1
  label_smoothing:
    smoothing: 0.4
    per_epoch_decay: 0.95
    train_correct_threshold: 0.95
  topo_scheduler:

    type: "constant"
    lam: 1000

    # type: "exp_epoch"
    lam_topo_per_epoch_decay: 1.0069
    max_lam: 0.00201
    # lam: 0.00001


    
    

    #type: "on_off"
    tracked_metric: "train_correct_epoch"
    metric_threshold: 0.25
    lam_high: 0.01
    lam_low: 0.000001


    #type: "match_mil_loss"
    #tracked_metric: "train_correct_epoch"
    #metric_threshold: 0.1
    active_high: True
    match_on_step: False
    default_value: 0.0


trainer_params:
  precision: '32'
  max_epochs: 2
  accumulate_grad_batches : 24

logging_params:
  project_name: "Masters_Project_Topo"
  save_dir: "logs/topo_gray_image_image_input_experiment/"
  name: "topo_eucl_gray_image_image_input_experiment"
  manual_seed: 1265
  
ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0
  patience: 100
  mode: 'min'