model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    dropout_encoder: 0.1
    pretrained_encoder: True
    input_type: "images"
    lam_topo: 0.000025
    label_smoothing: 0.1
    lam_topo_per_epoch_decay: 1.008
    max_lam: 0.01
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 4
    k_fold : -1 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    input_type: "images"
    topo_settings:
      normalize_distance_matricies: True
      nb_of_grouped_bags: 5
      dataset_settings:
        grayscale: False
        encode_with_dino_bloom: True
      embedding_settings:
        function_name: "UMAP"
        function_settings:
          n_components: 8


exp_type: "topo_SCEMILA_experiment"


exp_params:
  num_class: 5
  class_weighting_factor: 0.5
  optimizer: 
    name: "Adam"
    config:
      LR: 0.0001
      weight_decay: 0.00006
      scheduler: "ReduceLROnPlateau"
      patience: 8
      factor: 0.5
      monitor_metric: "val_mil_loss"
    batch_size: 1

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 200
  accumulate_grad_batches : 24

logging_params:
  project_name: "Masters_Project_Topo"
  save_dir: "logs/topo_dino_image_input_experiment/"
  name: "topo_dino_image_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0
  patience: 100
  mode: 'min'
