model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    input_type: "dino_bloom_small"
    lam_topo: 1
    lam_topo_per_epoch_decay: 0.955
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 4
    k_fold : -1 #set to one if no cross validation wanted
    encode_with_dino_bloom: True
    input_type: "images"
    topo_settings:
      normalize_distance_matricies: True
      nb_of_grouped_bags: 5
      dataset_settings:
        grayscale: False
        encode_with_dino_bloom: True
      embedding_settings:
        function_name: "UMAP"
        function_settings:
          n_components: 8


exp_type: "topo_SCEMILA_experiment"


exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      weight_decay: 0.001
      scheduler: "ReduceLROnPlateau"
      patience: 2
      factor: 0.5
    batch_size: 1

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  enable_progress_bar: False
  max_epochs: 50
  accumulate_grad_batches : 1

logging_params:
  project_name: "Masters_Project"
  save_dir: "logs/topo_dino_dino_input_experiment/"
  name: "topo_dino_dino_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0.1
  patience: 25
  mode: 'min'
