model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    input_type: "images"
    lam_topo: 1
    dropout_encoder: 0.0
    pretrained_encoder: False
    lam_topo_per_epoch_decay: 0.955
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 4
    k_fold : -1 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    gpu: True
    input_type: "images"
    topo_settings:
      nb_of_grouped_bags: 5
      normalize_distance_matricies: True
      dataset_settings:
        grayscale: True
        encode_with_dino_bloom: False



exp_type: "topo_SCEMILA_experiment"


exp_params:
  num_class: 5
  class_weighting: False
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      factor: 0.5
      weight_decay: 0.001
      scheduler: "ReduceLROnPlateau"
      patience: 2
    batch_size: 1

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 50
  accumulate_grad_batches : 1

logging_params:
  project_name: "Masters_Project"
  save_dir: "logs/topo_gray_image_image_input_experiment/"
  name: "topo_eucl_gray_image_image_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0.1
  patience: 25
  mode: 'min'