model_params:
  name: 'TopoSCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    dropout_encoder: 0.2
    pretrained_encoder: True
    input_type: "images"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 4
    k_fold : -1 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    input_type: "images"
    balance_dataset_classes: 40
    augmentation_settings: ["none",0.0]
    topo_settings:
      normalize_distance_matricies: True
      nb_of_grouped_bags: 5
      dataset_settings:
        grayscale: False
        encode_with_dino_bloom: True
      embedding_settings:
        function_name: "UMAP"
        function_settings:
          n_components: 8


exp_type: "topo_SCEMILA_experiment"


exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      weight_decay: 0.00035
      scheduler: "ReduceLROnPlateau"
      patience: 10
      factor: 0.5
      monitor_metric: "val_mil_loss"
    batch_size: 1
  topo_scheduler:
    type: "on_off"
    tracked_metric: "train_mil_loss_epoch"
    metric_threshold: 0.95
    max_lam: 0.01
    min_lam: 0.000001
  label_smoothing:
    smoothing: 0.4
    per_epoch_decay: 0.9
    train_correct_threshold: 0.95

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 200
  enable_progress_bar: False
  accumulate_grad_batches : 24

logging_params:
  project_name: "Masters_Project_Topo"
  save_dir: "logs/topo_dino_image_input_experiment/"
  name: "topo_dino_image_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0
  patience: 100
  mode: 'min'
