defaults:
  - baseline18
  - _self_

model_params:
  name: 'TopoSCEMILA'
  config:
    aggregator_type: "avg"
    topological_regularizer_settings:
      method: "deep" #=["match_scale_order","match_scale_distribution","moor_method","modified_moor_method","deep"] "og_moor"
      multithreading: True
      timeout: 1

dataset:
  config:
    gpu: True
    num_workers: 8
    topo_settings:
      balance_dataset_classes: 50
      nb_of_grouped_bags: 1
      normalize_distance_matricies: True
      dataset_settings:
        grayscale: False
        encode_with_dino_bloom: True

exp_type: "topo_SCEMILA_experiment"
exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      weight_decay: 0.00035
      factor: 0.5
      scheduler: "ReduceLROnPlateau"
      patience: 30
      monitor_metric: "val_correct_epoch"
      mode: "max"
    batch_size: 1
  topo_scheduler:
    type: "constant"
    lam: 1

trainer_params:
  precision: 16

logging_params:
  save_dir: "logs/topo_dino_image_input_experiment/"
  name: "res18_avg_8worker_16prec_opt_deep"
  manual_seed: 1265