name: rgb_res18_sweep
program: hyperparameter_sweeper/train_injection_script.py
project: new_param_sweep
method: bayes  # or grid, random
metric:
  name: accuracy
  goal: maximize
parameters:
  base_config_path:
    values: ["configs/SCEMILA_approaches/normal/opt_image_input.yaml"] # "configs/SCEMILA_approaches/normal/opt_image_input.yaml"
  model_params.config.label_smoothing:
    min: 0.0
    max: 0.3
  model_params.config.dropout_encoder:
    min: 0.05
    max: 0.4
  model_params.config.pretrained_encoder:
    values: [True,True,False]
  dataset.config.augmentation_settings:
    values: ["none",["all",0.025],["all",0.05],["all",0.1]]
  dataset.config.balance_dataset_classes:
    values: [30,40,50]
  exp_params.optimizer.config.LR:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  exp_params.optimizer.config.weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  exp_params.optimizer.config.factor:
    distribution: log_uniform_values
    min: 0.4
    max: 0.7
  exp_params.optimizer.config.patience:
    values: [8,10]
  trainer_params.accumulate_grad_batches:
    values: [1, 18, 36]
  trainer_params.max_epochs:
    values: [300,350] 
  ES_params.patience:
    values: [30,60,90]
  ES_params.min_delta:
    values: [0.01]
  dataset.config.k_fold:
    values: [-1]
  exp_params.class_weighting_factor:
    values: [0.0,0.0,0.5]
