name: topo_gray_image_topo_sweep
program: hyperparameter_sweeper/train_injection_script.py
project: param_sweep
method: bayes  # or grid, random
metric:
  name: accuracy
  goal: maximize
parameters:
  base_config_path:
    values: ["configs/SCEMILA_approaches/topo/topo_eucl_gray_image_image_input.yaml"] # "configs/SCEMILA_approaches/normal/opt_image_input.yaml"
  dataset.config.topo_settings.normalize_distance_matricies:
    values: [True,True,False]
  exp_params.optimizer.config.factor:
    min: 0.4
    max: 0.6
  exp_params.optimizer.config.patience:
    values: [8,10]
  trainer_params.accumulate_grad_batches:
    values: [24]
  trainer_params.max_epochs:
    values: [300,350] 
  ES_params.patience:
    values: [50]
  ES_params.min_delta:
    values: [0.01]
  dataset.config.k_fold:
    values: [-1]

