model_params:
  name: 'SCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    dropout_encoder: 0.2
    pretrained_encoder: True
    input_type: "images"
    #load_encoder_weights: "data/ResNet18Weights/TopoOnlyWeights/1.88_mil_4it_e1000.ckpt"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 6
    val_split: 0.25 # is a dummy variable in this cae since kfold is set
    k_fold : 4 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    input_type: "images"
    gpu: True
    balance_dataset_classes: 50
    augmentation_settings: ["all",0.2]


exp_type: "SCEMILA_experiment"
exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      weight_decay: 0.0000005
      factor: 0.99
      scheduler: "ReduceLROnPlateau"
      patience: 30
      monitor_metric: "val_correct_epoch"
      mode: "max"
    batch_size: 1
  label_smoothing:
    smoothing: 0.03
    per_epoch_decay: 0.999
    train_correct_threshold: 1.01 #never

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 200
  enable_progress_bar: False
  accumulate_grad_batches: 64


logging_params:
  project_name: "reg_testingv2"
  save_dir: "logs/image_input_experiment/"
  name: "baseline_resnet34_weakextraconv_strgAug"
  manual_seed: 1265

ES_params:
  monitor: 'val_correct_epoch'
  min_delta: 0.01
  patience: 80
  mode: 'max'