model_params:
  name: 'SCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda"
    dropout_encoder: 0.1
    pretrained_encoder: True
    input_type: "images"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 6
    val_split: 0.25 # is a dummy variable in this cae since kfold is set
    k_fold : 4 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    input_type: "images"
    gpu: True
    balance_dataset_classes: 40
    augmentation_settings: ["all",0.05]


exp_type: "SCEMILA_experiment"
exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      weight_decay: 0.00035
      factor: 0.8
      scheduler: "ReduceLROnPlateau"
      patience: 20
      monitor_metric: "val_correct_epoch"
      mode: "max"
    batch_size: 1
  label_smoothing:
    smoothing: 0.15
    per_epoch_decay: 1.0
    train_correct_threshold: 0.97
    default_value: 0.15

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 250
  enable_progress_bar: False
  accumulate_grad_batches: 36


logging_params:
  project_name: "Masters_Project_Opt"
  save_dir: "logs/image_input_experiment/"
  name: "image_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_correct_epoch'
  min_delta: 0.01
  patience: 100
  mode: 'max'