model_params:
  name: 'SCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cuda:0"
    input_type: "fnl34"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 4
    k_fold : -1
    encode_with_dino_bloom: False
    input_type: "fnl34"
 
exp_type: "SCEMILA_experiment"

exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "SGD"
    config:
      LR: 0.00005
      momentum: 0.9
      nestrov: True
    batch_size: 1
  label_smoothing:
    smoothing: 0.4
    per_epoch_decay: 0.9
    train_correct_threshold: 0.95

trainer_params:
  precision: '32'
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 50
  accumulate_grad_batches : 1
  enable_progress_bar: False

logging_params:
  project_name: "Masters_Project"
  save_dir: "logs/fnl34_input_experiment/"
  name: "fnl34_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0.1
  patience: 25
  mode: 'min'
