model_params:
  name: 'SCEMILA'
  config:
    multicolumn: 1
    class_count: 5
    device: "cpu"
    dropout_encoder: 0.2
    pretrained_encoder: False
    input_type: "images"
            
dataset:
  name: 'SCEMILA'
  config:
    num_workers: 1
    k_fold : 4 #set to one if no cross validation wanted
    encode_with_dino_bloom: False
    input_type: "images"
    gpu: False
    balance_dataset_classes: 10
    augmentation_settings: null


exp_type: "SCEMILA_experiment"
exp_params:
  num_class: 5
  class_weighting_factor: 0.0
  optimizer: 
    name: "Adam"
    config:
      LR: 0.00005
      weight_decay: 0.001
      factor: 0.5
      scheduler: "ReduceLROnPlateau"
      patience: 2
      monitor_metric: "val_mil_loss"
    batch_size: 1
  label_smoothing:
    smoothing: 0.4
    per_epoch_decay: 0.95
    train_correct_threshold: 0.95


trainer_params:
  precision: '32'
  max_epochs: 2
  accumulate_grad_batches : 24


logging_params:
  project_name: "Masters_Project"
  save_dir: "logs/image_input_experiment/"
  name: "image_input_experiment"
  manual_seed: 1265

ES_params:
  monitor: 'val_mil_loss_epoch'
  min_delta: 0
  patience: 100
  mode: 'min'